// Mocks generated by Mockito 5.4.6 from annotations
// in jawara/test/integration/daftar_warga_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:jawara/data/models/keluarga.dart' as _i3;
import 'package:jawara/data/models/warga_profile.dart' as _i2;
import 'package:jawara/data/repositories/warga_repositories.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWargaProfile_0 extends _i1.SmartFake implements _i2.WargaProfile {
  _FakeWargaProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeluarga_1 extends _i1.SmartFake implements _i3.Keluarga {
  _FakeKeluarga_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WargaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWargaRepository extends _i1.Mock implements _i4.WargaRepository {
  MockWargaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WargaProfile> createProfile({
    required String? userId,
    required String? namaLengkap,
    required String? nik,
    required String? noHp,
    required String? jenisKelamin,
    required String? agama,
    required String? golonganDarah,
    required String? pekerjaan,
    required String? peranKeluarga,
    String? fotoIdentitasUrl,
    String? tempatLahir,
    String? tanggalLahir,
    String? pendidikan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [],
          {
            #userId: userId,
            #namaLengkap: namaLengkap,
            #nik: nik,
            #noHp: noHp,
            #jenisKelamin: jenisKelamin,
            #agama: agama,
            #golonganDarah: golonganDarah,
            #pekerjaan: pekerjaan,
            #peranKeluarga: peranKeluarga,
            #fotoIdentitasUrl: fotoIdentitasUrl,
            #tempatLahir: tempatLahir,
            #tanggalLahir: tanggalLahir,
            #pendidikan: pendidikan,
          },
        ),
        returnValue: _i5.Future<_i2.WargaProfile>.value(_FakeWargaProfile_0(
          this,
          Invocation.method(
            #createProfile,
            [],
            {
              #userId: userId,
              #namaLengkap: namaLengkap,
              #nik: nik,
              #noHp: noHp,
              #jenisKelamin: jenisKelamin,
              #agama: agama,
              #golonganDarah: golonganDarah,
              #pekerjaan: pekerjaan,
              #peranKeluarga: peranKeluarga,
              #fotoIdentitasUrl: fotoIdentitasUrl,
              #tempatLahir: tempatLahir,
              #tanggalLahir: tanggalLahir,
              #pendidikan: pendidikan,
            },
          ),
        )),
      ) as _i5.Future<_i2.WargaProfile>);

  @override
  _i5.Future<_i2.WargaProfile?> getProfileById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileById,
          [userId],
        ),
        returnValue: _i5.Future<_i2.WargaProfile?>.value(),
      ) as _i5.Future<_i2.WargaProfile?>);

  @override
  _i5.Future<_i2.WargaProfile?> getProfileByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileByEmail,
          [email],
        ),
        returnValue: _i5.Future<_i2.WargaProfile?>.value(),
      ) as _i5.Future<_i2.WargaProfile?>);

  @override
  _i5.Future<_i2.WargaProfile> updateProfile(_i2.WargaProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i5.Future<_i2.WargaProfile>.value(_FakeWargaProfile_0(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i5.Future<_i2.WargaProfile>);

  @override
  _i5.Future<void> deleteProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> uploadFoto({
    required String? userId,
    required _i6.File? fotoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFoto,
          [],
          {
            #userId: userId,
            #fotoFile: fotoFile,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadFoto,
            [],
            {
              #userId: userId,
              #fotoFile: fotoFile,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  String getFotoPublicUrl(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #getFotoPublicUrl,
          [filePath],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getFotoPublicUrl,
            [filePath],
          ),
        ),
      ) as String);

  @override
  _i5.Future<_i3.Keluarga?> getKeluargaByKepalakeluargaId(
          String? kepalakeluargaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeluargaByKepalakeluargaId,
          [kepalakeluargaId],
        ),
        returnValue: _i5.Future<_i3.Keluarga?>.value(),
      ) as _i5.Future<_i3.Keluarga?>);

  @override
  _i5.Future<_i3.Keluarga> createKeluarga({
    required String? kepalakeluargaId,
    required String? nomorKk,
    String? rumahId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKeluarga,
          [],
          {
            #kepalakeluargaId: kepalakeluargaId,
            #nomorKk: nomorKk,
            #rumahId: rumahId,
          },
        ),
        returnValue: _i5.Future<_i3.Keluarga>.value(_FakeKeluarga_1(
          this,
          Invocation.method(
            #createKeluarga,
            [],
            {
              #kepalakeluargaId: kepalakeluargaId,
              #nomorKk: nomorKk,
              #rumahId: rumahId,
            },
          ),
        )),
      ) as _i5.Future<_i3.Keluarga>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllKeluarga() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllKeluarga,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllWarga() => (super.noSuchMethod(
        Invocation.method(
          #getAllWarga,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> linkWargaToKeluarga(
    String? wargaId,
    String? keluargaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWargaToKeluarga,
          [
            wargaId,
            keluargaId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRumahList() => (super.noSuchMethod(
        Invocation.method(
          #getRumahList,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updateRumahStatusToOccupied(String? rumahId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRumahStatusToOccupied,
          [rumahId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> createMutasi({
    required String? keluargaId,
    required String? rumahId,
    required DateTime? tanggalMutasi,
    required String? alasanMutasi,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMutasi,
          [],
          {
            #keluargaId: keluargaId,
            #rumahId: rumahId,
            #tanggalMutasi: tanggalMutasi,
            #alasanMutasi: alasanMutasi,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMutasiList() => (super.noSuchMethod(
        Invocation.method(
          #getMutasiList,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updateRumahStatus(
    String? rumahId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRumahStatus,
          [
            rumahId,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllPenghuni() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPenghuni,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updatePenghuniRumah(
    String? penghuniId,
    String? newRumahId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePenghuniRumah,
          [
            penghuniId,
            newRumahId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePenghuni(String? penghuniId) => (super.noSuchMethod(
        Invocation.method(
          #deletePenghuni,
          [penghuniId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createPenghuni({
    required String? keluargaId,
    required String? rumahId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPenghuni,
          [],
          {
            #keluargaId: keluargaId,
            #rumahId: rumahId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateKeluargaAlamat(
    String? keluargaId,
    String? alamatId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKeluargaAlamat,
          [
            keluargaId,
            alamatId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateWarga({
    required String? wargaId,
    required String? namaLengkap,
    required String? nik,
    required String? noTelepon,
    required String? jenisKelamin,
    required String? agama,
    required String? golonganDarah,
    required String? pekerjaan,
    required String? peranKeluarga,
    String? keluargaId,
    String? tempatLahir,
    String? tanggalLahir,
    String? pendidikan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWarga,
          [],
          {
            #wargaId: wargaId,
            #namaLengkap: namaLengkap,
            #nik: nik,
            #noTelepon: noTelepon,
            #jenisKelamin: jenisKelamin,
            #agama: agama,
            #golonganDarah: golonganDarah,
            #pekerjaan: pekerjaan,
            #peranKeluarga: peranKeluarga,
            #keluargaId: keluargaId,
            #tempatLahir: tempatLahir,
            #tanggalLahir: tanggalLahir,
            #pendidikan: pendidikan,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteWarga(String? wargaId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWarga,
          [wargaId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
