// Mocks generated by Mockito 5.4.6 from annotations
// in jawara/test/integration/kelola_keuangan_harian.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:jawara/data/models/kegiatan_model.dart' as _i2;
import 'package:jawara/data/models/pengeluaran_model.dart' as _i3;
import 'package:jawara/data/repositories/kegiatan_repository.dart' as _i4;
import 'package:jawara/data/repositories/pengeluaran_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKegiatanModel_0 extends _i1.SmartFake implements _i2.KegiatanModel {
  _FakeKegiatanModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePengeluaranModel_1 extends _i1.SmartFake
    implements _i3.PengeluaranModel {
  _FakePengeluaranModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KegiatanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKegiatanRepository extends _i1.Mock
    implements _i4.KegiatanRepository {
  MockKegiatanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.KegiatanModel>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.KegiatanModel>>.value(<_i2.KegiatanModel>[]),
      ) as _i5.Future<List<_i2.KegiatanModel>>);

  @override
  _i5.Future<_i2.KegiatanModel> createKegiatan({
    required String? nama,
    required String? kategori,
    DateTime? tanggal,
    String? lokasi,
    String? penanggungJawab,
    String? deskripsi,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKegiatan,
          [],
          {
            #nama: nama,
            #kategori: kategori,
            #tanggal: tanggal,
            #lokasi: lokasi,
            #penanggungJawab: penanggungJawab,
            #deskripsi: deskripsi,
          },
        ),
        returnValue: _i5.Future<_i2.KegiatanModel>.value(_FakeKegiatanModel_0(
          this,
          Invocation.method(
            #createKegiatan,
            [],
            {
              #nama: nama,
              #kategori: kategori,
              #tanggal: tanggal,
              #lokasi: lokasi,
              #penanggungJawab: penanggungJawab,
              #deskripsi: deskripsi,
            },
          ),
        )),
      ) as _i5.Future<_i2.KegiatanModel>);

  @override
  _i5.Future<_i2.KegiatanModel> updateKegiatan({
    required String? id,
    required String? nama,
    required String? kategori,
    DateTime? tanggal,
    String? lokasi,
    String? penanggungJawab,
    String? deskripsi,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKegiatan,
          [],
          {
            #id: id,
            #nama: nama,
            #kategori: kategori,
            #tanggal: tanggal,
            #lokasi: lokasi,
            #penanggungJawab: penanggungJawab,
            #deskripsi: deskripsi,
          },
        ),
        returnValue: _i5.Future<_i2.KegiatanModel>.value(_FakeKegiatanModel_0(
          this,
          Invocation.method(
            #updateKegiatan,
            [],
            {
              #id: id,
              #nama: nama,
              #kategori: kategori,
              #tanggal: tanggal,
              #lokasi: lokasi,
              #penanggungJawab: penanggungJawab,
              #deskripsi: deskripsi,
            },
          ),
        )),
      ) as _i5.Future<_i2.KegiatanModel>);

  @override
  _i5.Future<void> deleteKegiatan(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteKegiatan,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [PengeluaranRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPengeluaranRepository extends _i1.Mock
    implements _i6.PengeluaranRepository {
  MockPengeluaranRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.PengeluaranModel>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i5.Future<List<_i3.PengeluaranModel>>.value(
            <_i3.PengeluaranModel>[]),
      ) as _i5.Future<List<_i3.PengeluaranModel>>);

  @override
  _i5.Future<_i3.PengeluaranModel> createPengeluaran({
    required String? nama,
    required DateTime? tanggal,
    required String? kategori,
    required double? jumlah,
    String? bukti,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPengeluaran,
          [],
          {
            #nama: nama,
            #tanggal: tanggal,
            #kategori: kategori,
            #jumlah: jumlah,
            #bukti: bukti,
          },
        ),
        returnValue:
            _i5.Future<_i3.PengeluaranModel>.value(_FakePengeluaranModel_1(
          this,
          Invocation.method(
            #createPengeluaran,
            [],
            {
              #nama: nama,
              #tanggal: tanggal,
              #kategori: kategori,
              #jumlah: jumlah,
              #bukti: bukti,
            },
          ),
        )),
      ) as _i5.Future<_i3.PengeluaranModel>);

  @override
  _i5.Future<_i3.PengeluaranModel> updatePengeluaran({
    required String? id,
    required String? nama,
    required DateTime? tanggal,
    required String? kategori,
    required double? jumlah,
    String? bukti,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePengeluaran,
          [],
          {
            #id: id,
            #nama: nama,
            #tanggal: tanggal,
            #kategori: kategori,
            #jumlah: jumlah,
            #bukti: bukti,
          },
        ),
        returnValue:
            _i5.Future<_i3.PengeluaranModel>.value(_FakePengeluaranModel_1(
          this,
          Invocation.method(
            #updatePengeluaran,
            [],
            {
              #id: id,
              #nama: nama,
              #tanggal: tanggal,
              #kategori: kategori,
              #jumlah: jumlah,
              #bukti: bukti,
            },
          ),
        )),
      ) as _i5.Future<_i3.PengeluaranModel>);

  @override
  _i5.Future<void> deletePengeluaran(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePengeluaran,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> uploadBukti(
    String? path,
    List<int>? fileBytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBukti,
          [
            path,
            fileBytes,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBukti,
            [
              path,
              fileBytes,
            ],
          ),
        )),
      ) as _i5.Future<String>);
}
