// Mocks generated by Mockito 5.4.6 from annotations
// in jawara/test/integration/pemasukan_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jawara/data/models/pemasukan_model.dart' as _i2;
import 'package:jawara/data/repositories/pemasukan_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePemasukanModel_0 extends _i1.SmartFake
    implements _i2.PemasukanModel {
  _FakePemasukanModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PemasukanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPemasukanRepository extends _i1.Mock
    implements _i3.PemasukanRepository {
  MockPemasukanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PemasukanModel>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.PemasukanModel>>.value(<_i2.PemasukanModel>[]),
      ) as _i4.Future<List<_i2.PemasukanModel>>);

  @override
  _i4.Future<_i2.PemasukanModel?> fetchById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchById,
          [id],
        ),
        returnValue: _i4.Future<_i2.PemasukanModel?>.value(),
      ) as _i4.Future<_i2.PemasukanModel?>);

  @override
  _i4.Future<_i2.PemasukanModel> createPemasukan({
    required String? nama_pemasukan,
    required DateTime? tanggal_pemasukan,
    required String? kategori_pemasukan,
    required double? jumlah,
    String? bukti_pemasukan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPemasukan,
          [],
          {
            #nama_pemasukan: nama_pemasukan,
            #tanggal_pemasukan: tanggal_pemasukan,
            #kategori_pemasukan: kategori_pemasukan,
            #jumlah: jumlah,
            #bukti_pemasukan: bukti_pemasukan,
          },
        ),
        returnValue: _i4.Future<_i2.PemasukanModel>.value(_FakePemasukanModel_0(
          this,
          Invocation.method(
            #createPemasukan,
            [],
            {
              #nama_pemasukan: nama_pemasukan,
              #tanggal_pemasukan: tanggal_pemasukan,
              #kategori_pemasukan: kategori_pemasukan,
              #jumlah: jumlah,
              #bukti_pemasukan: bukti_pemasukan,
            },
          ),
        )),
      ) as _i4.Future<_i2.PemasukanModel>);

  @override
  _i4.Future<_i2.PemasukanModel> updatePemasukan({
    required String? id,
    required String? nama_pemasukan,
    required DateTime? tanggal_pemasukan,
    required String? kategori_pemasukan,
    required double? jumlah,
    String? bukti_pemasukan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePemasukan,
          [],
          {
            #id: id,
            #nama_pemasukan: nama_pemasukan,
            #tanggal_pemasukan: tanggal_pemasukan,
            #kategori_pemasukan: kategori_pemasukan,
            #jumlah: jumlah,
            #bukti_pemasukan: bukti_pemasukan,
          },
        ),
        returnValue: _i4.Future<_i2.PemasukanModel>.value(_FakePemasukanModel_0(
          this,
          Invocation.method(
            #updatePemasukan,
            [],
            {
              #id: id,
              #nama_pemasukan: nama_pemasukan,
              #tanggal_pemasukan: tanggal_pemasukan,
              #kategori_pemasukan: kategori_pemasukan,
              #jumlah: jumlah,
              #bukti_pemasukan: bukti_pemasukan,
            },
          ),
        )),
      ) as _i4.Future<_i2.PemasukanModel>);

  @override
  _i4.Future<void> deletePemasukan(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePemasukan,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.PemasukanModel>> filterPemasukan({
    String? nama,
    String? kategori,
    DateTime? fromDate,
    DateTime? toDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterPemasukan,
          [],
          {
            #nama: nama,
            #kategori: kategori,
            #fromDate: fromDate,
            #toDate: toDate,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.PemasukanModel>>.value(<_i2.PemasukanModel>[]),
      ) as _i4.Future<List<_i2.PemasukanModel>>);

  @override
  _i4.Future<List<String>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<String> uploadBukti(
    String? path,
    List<int>? fileBytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBukti,
          [
            path,
            fileBytes,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBukti,
            [
              path,
              fileBytes,
            ],
          ),
        )),
      ) as _i4.Future<String>);
}
