// Mocks generated by Mockito 5.4.6 from annotations
// in jawara/test/integration/pembayaran_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jawara/data/models/metode_pembayaran_model.dart' as _i2;
import 'package:jawara/data/repositories/metode_pembayaran_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMetodePembayaranModel_0 extends _i1.SmartFake
    implements _i2.MetodePembayaranModel {
  _FakeMetodePembayaranModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MetodePembayaranRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetodePembayaranRepository extends _i1.Mock
    implements _i3.MetodePembayaranRepository {
  MockMetodePembayaranRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MetodePembayaranModel>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.MetodePembayaranModel>>.value(
            <_i2.MetodePembayaranModel>[]),
      ) as _i4.Future<List<_i2.MetodePembayaranModel>>);

  @override
  _i4.Future<_i2.MetodePembayaranModel> createMetodePembayaran({
    required String? namaMetode,
    String? nomorRekening,
    String? namaPemilik,
    String? fotoBarcode,
    String? thumbnail,
    String? catatan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMetodePembayaran,
          [],
          {
            #namaMetode: namaMetode,
            #nomorRekening: nomorRekening,
            #namaPemilik: namaPemilik,
            #fotoBarcode: fotoBarcode,
            #thumbnail: thumbnail,
            #catatan: catatan,
          },
        ),
        returnValue: _i4.Future<_i2.MetodePembayaranModel>.value(
            _FakeMetodePembayaranModel_0(
          this,
          Invocation.method(
            #createMetodePembayaran,
            [],
            {
              #namaMetode: namaMetode,
              #nomorRekening: nomorRekening,
              #namaPemilik: namaPemilik,
              #fotoBarcode: fotoBarcode,
              #thumbnail: thumbnail,
              #catatan: catatan,
            },
          ),
        )),
      ) as _i4.Future<_i2.MetodePembayaranModel>);

  @override
  _i4.Future<_i2.MetodePembayaranModel> updateMetodePembayaran({
    required String? id,
    required String? namaMetode,
    String? nomorRekening,
    String? namaPemilik,
    String? fotoBarcode,
    String? thumbnail,
    String? catatan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMetodePembayaran,
          [],
          {
            #id: id,
            #namaMetode: namaMetode,
            #nomorRekening: nomorRekening,
            #namaPemilik: namaPemilik,
            #fotoBarcode: fotoBarcode,
            #thumbnail: thumbnail,
            #catatan: catatan,
          },
        ),
        returnValue: _i4.Future<_i2.MetodePembayaranModel>.value(
            _FakeMetodePembayaranModel_0(
          this,
          Invocation.method(
            #updateMetodePembayaran,
            [],
            {
              #id: id,
              #namaMetode: namaMetode,
              #nomorRekening: nomorRekening,
              #namaPemilik: namaPemilik,
              #fotoBarcode: fotoBarcode,
              #thumbnail: thumbnail,
              #catatan: catatan,
            },
          ),
        )),
      ) as _i4.Future<_i2.MetodePembayaranModel>);

  @override
  _i4.Future<void> deleteMetodePembayaran(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMetodePembayaran,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
