// Mocks generated by Mockito 5.4.6 from annotations
// in jawara/test/integration/register_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;

import 'package:jawara/core/services/auth_services.dart' as _i5;
import 'package:jawara/data/models/keluarga.dart' as _i4;
import 'package:jawara/data/models/warga_profile.dart' as _i3;
import 'package:jawara/data/repositories/warga_repositories.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWargaProfile_1 extends _i1.SmartFake implements _i3.WargaProfile {
  _FakeWargaProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeluarga_2 extends _i1.SmartFake implements _i4.Keluarga {
  _FakeKeluarga_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AuthResponse> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<_i2.AuthResponse> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [WargaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWargaRepository extends _i1.Mock implements _i7.WargaRepository {
  MockWargaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.WargaProfile> createProfile({
    required String? userId,
    required String? namaLengkap,
    required String? nik,
    required String? noHp,
    required String? jenisKelamin,
    required String? agama,
    required String? golonganDarah,
    required String? pekerjaan,
    required String? peranKeluarga,
    String? fotoIdentitasUrl,
    String? tempatLahir,
    String? tanggalLahir,
    String? pendidikan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [],
          {
            #userId: userId,
            #namaLengkap: namaLengkap,
            #nik: nik,
            #noHp: noHp,
            #jenisKelamin: jenisKelamin,
            #agama: agama,
            #golonganDarah: golonganDarah,
            #pekerjaan: pekerjaan,
            #peranKeluarga: peranKeluarga,
            #fotoIdentitasUrl: fotoIdentitasUrl,
            #tempatLahir: tempatLahir,
            #tanggalLahir: tanggalLahir,
            #pendidikan: pendidikan,
          },
        ),
        returnValue: _i6.Future<_i3.WargaProfile>.value(_FakeWargaProfile_1(
          this,
          Invocation.method(
            #createProfile,
            [],
            {
              #userId: userId,
              #namaLengkap: namaLengkap,
              #nik: nik,
              #noHp: noHp,
              #jenisKelamin: jenisKelamin,
              #agama: agama,
              #golonganDarah: golonganDarah,
              #pekerjaan: pekerjaan,
              #peranKeluarga: peranKeluarga,
              #fotoIdentitasUrl: fotoIdentitasUrl,
              #tempatLahir: tempatLahir,
              #tanggalLahir: tanggalLahir,
              #pendidikan: pendidikan,
            },
          ),
        )),
      ) as _i6.Future<_i3.WargaProfile>);

  @override
  _i6.Future<_i3.WargaProfile?> getProfileById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileById,
          [userId],
        ),
        returnValue: _i6.Future<_i3.WargaProfile?>.value(),
      ) as _i6.Future<_i3.WargaProfile?>);

  @override
  _i6.Future<_i3.WargaProfile?> getProfileByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileByEmail,
          [email],
        ),
        returnValue: _i6.Future<_i3.WargaProfile?>.value(),
      ) as _i6.Future<_i3.WargaProfile?>);

  @override
  _i6.Future<_i3.WargaProfile> updateProfile(_i3.WargaProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i6.Future<_i3.WargaProfile>.value(_FakeWargaProfile_1(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i6.Future<_i3.WargaProfile>);

  @override
  _i6.Future<void> deleteProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> uploadFoto({
    required String? userId,
    required _i8.File? fotoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFoto,
          [],
          {
            #userId: userId,
            #fotoFile: fotoFile,
          },
        ),
        returnValue: _i6.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadFoto,
            [],
            {
              #userId: userId,
              #fotoFile: fotoFile,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  String getFotoPublicUrl(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #getFotoPublicUrl,
          [filePath],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getFotoPublicUrl,
            [filePath],
          ),
        ),
      ) as String);

  @override
  _i6.Future<_i4.Keluarga?> getKeluargaByKepalakeluargaId(
          String? kepalakeluargaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeluargaByKepalakeluargaId,
          [kepalakeluargaId],
        ),
        returnValue: _i6.Future<_i4.Keluarga?>.value(),
      ) as _i6.Future<_i4.Keluarga?>);

  @override
  _i6.Future<_i4.Keluarga> createKeluarga({
    required String? kepalakeluargaId,
    required String? nomorKk,
    String? rumahId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKeluarga,
          [],
          {
            #kepalakeluargaId: kepalakeluargaId,
            #nomorKk: nomorKk,
            #rumahId: rumahId,
          },
        ),
        returnValue: _i6.Future<_i4.Keluarga>.value(_FakeKeluarga_2(
          this,
          Invocation.method(
            #createKeluarga,
            [],
            {
              #kepalakeluargaId: kepalakeluargaId,
              #nomorKk: nomorKk,
              #rumahId: rumahId,
            },
          ),
        )),
      ) as _i6.Future<_i4.Keluarga>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllKeluarga() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllKeluarga,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllWarga() => (super.noSuchMethod(
        Invocation.method(
          #getAllWarga,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> linkWargaToKeluarga(
    String? wargaId,
    String? keluargaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWargaToKeluarga,
          [
            wargaId,
            keluargaId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getRumahList() => (super.noSuchMethod(
        Invocation.method(
          #getRumahList,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> updateRumahStatusToOccupied(String? rumahId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRumahStatusToOccupied,
          [rumahId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> createMutasi({
    required String? keluargaId,
    required String? rumahId,
    required DateTime? tanggalMutasi,
    required String? alasanMutasi,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMutasi,
          [],
          {
            #keluargaId: keluargaId,
            #rumahId: rumahId,
            #tanggalMutasi: tanggalMutasi,
            #alasanMutasi: alasanMutasi,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getMutasiList() => (super.noSuchMethod(
        Invocation.method(
          #getMutasiList,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> updateRumahStatus(
    String? rumahId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRumahStatus,
          [
            rumahId,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllPenghuni() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPenghuni,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> updatePenghuniRumah(
    String? penghuniId,
    String? newRumahId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePenghuniRumah,
          [
            penghuniId,
            newRumahId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deletePenghuni(String? penghuniId) => (super.noSuchMethod(
        Invocation.method(
          #deletePenghuni,
          [penghuniId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createPenghuni({
    required String? keluargaId,
    required String? rumahId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPenghuni,
          [],
          {
            #keluargaId: keluargaId,
            #rumahId: rumahId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateKeluargaAlamat(
    String? keluargaId,
    String? alamatId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKeluargaAlamat,
          [
            keluargaId,
            alamatId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateWarga({
    required String? wargaId,
    required String? namaLengkap,
    required String? nik,
    required String? noTelepon,
    required String? jenisKelamin,
    required String? agama,
    required String? golonganDarah,
    required String? pekerjaan,
    required String? peranKeluarga,
    String? keluargaId,
    String? tempatLahir,
    String? tanggalLahir,
    String? pendidikan,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWarga,
          [],
          {
            #wargaId: wargaId,
            #namaLengkap: namaLengkap,
            #nik: nik,
            #noTelepon: noTelepon,
            #jenisKelamin: jenisKelamin,
            #agama: agama,
            #golonganDarah: golonganDarah,
            #pekerjaan: pekerjaan,
            #peranKeluarga: peranKeluarga,
            #keluargaId: keluargaId,
            #tempatLahir: tempatLahir,
            #tanggalLahir: tanggalLahir,
            #pendidikan: pendidikan,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteWarga(String? wargaId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWarga,
          [wargaId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
